/**
 * Code Generators for Retro MS-DOS Development & Data Integration
 */

import { CompiledDosBinary, ConvertedAudioData } from '../types/dos';

/**
 * Generates C / C++ header file containing raw 8-bit audio array
 */
export function generateCHeader(audio: ConvertedAudioData, binary: CompiledDosBinary): string {
  const bytes = audio.raw8BitData;
  const sampleRate = audio.sampleRate;
  const length = bytes.length;
  const macroName = audio.audioName.toUpperCase().replace(/[^A-Z0-9]/g, '_');

  let hexDump = '';
  const bytesPerLine = 16;
  const maxBytesToFormat = Math.min(bytes.length, 1024); // format up to 1024 bytes in text preview

  for (let i = 0; i < maxBytesToFormat; i += bytesPerLine) {
    const chunk: string[] = [];
    for (let j = 0; j < bytesPerLine && (i + j) < maxBytesToFormat; j++) {
      chunk.push(`0x${bytes[i + j].toString(16).padStart(2, '0').toUpperCase()}`);
    }
    hexDump += `    ${chunk.join(', ')}${i + bytesPerLine < maxBytesToFormat ? ',' : ''}\n`;
  }

  const truncatedNotice = bytes.length > maxBytesToFormat 
    ? `\n    /* ... [${bytes.length - maxBytesToFormat} additional bytes omitted for preview] ... */\n` 
    : '';

  return `/**
 * Generated by DOS Audio MZ Studio
 * Audio Asset: ${audio.audioName}
 * Format: 8-bit Mono PCM
 * Sample Rate: ${sampleRate} Hz
 * Total Samples: ${length} bytes
 * Executable Offset in MZ EXE: 0x${binary.audioOffset.toString(16).toUpperCase()}
 */

#ifndef _DOS_AUDIO_${macroName}_H_
#define _DOS_AUDIO_${macroName}_H_

#define DOS_AUDIO_SAMPLE_RATE     ${sampleRate}
#define DOS_AUDIO_TOTAL_SAMPLES   ${length}
#define DOS_AUDIO_EXE_OFFSET      0x${binary.audioOffset.toString(16).toUpperCase()}

/* 8-bit unsigned PCM audio sample data */
static const unsigned char DOS_AUDIO_DATA[${length}] = {
${hexDump}${truncatedNotice}};

#endif /* _DOS_AUDIO_${macroName}_H_ */
`;
}

/**
 * Generates NASM / TASM x86 16-bit Assembly source code
 */
export function generateAsmSource(audio: ConvertedAudioData, binary: CompiledDosBinary): string {
  const sampleRate = audio.sampleRate;
  const bytes = audio.raw8BitData;
  const length = bytes.length;

  let dbStatements = '';
  const previewLimit = Math.min(bytes.length, 256);
  for (let i = 0; i < previewLimit; i += 16) {
    const chunk: string[] = [];
    for (let j = 0; j < 16 && (i + j) < previewLimit; j++) {
      chunk.push(`0${bytes[i + j].toString(16).padStart(2, '0').toUpperCase()}h`);
    }
    dbStatements += `    db ${chunk.join(', ')}\n`;
  }

  return `; ==============================================================================
; MS-DOS 16-BIT AUDIO PLAYER ROUTINE (NASM / TASM COMPATIBLE)
; Sample Rate: ${sampleRate} Hz | Samples: ${length} bytes
; Mode: ${binary.dosMode}
; ==============================================================================

BITS 16
ORG 100h                ; Standard .COM file entry or assemble with -f bin

SECTION .text
start:
    ; Print DOS welcome message
    mov ah, 09h
    mov dx, msg_play
    int 21h

    ; Initialize playback loop
    mov si, audio_samples   ; DS:SI points to 8-bit audio buffer
    mov cx, ${length}       ; Total samples counter

play_loop:
    lodsb                   ; Load sample byte into AL
    out 378h, al            ; Output to Covox LPT1 DAC (or write to PC speaker)

    ; Sample rate timing delay
    mov ah, 24
delay_loop:
    dec ah
    jnz delay_loop

    ; Poll keyboard (press any key to abort)
    mov ah, 01h
    int 16h
    jnz user_exit

    loop play_loop          ; Decrement CX and loop

user_exit:
    ; Clean up DAC and return to DOS
    xor al, al
    out 378h, al
    mov ax, 4C00h           ; INT 21h terminate program
    int 21h

SECTION .data
msg_play:
    db 0Dh, 0Ah, "[DOS AUDIO] Playing ${audio.audioName} (${sampleRate} Hz)...", 0Dh, 0Ah
    db "Press any key to exit to DOS.", 0Dh, 0Ah, "$"

audio_samples:
${dbStatements}    ; ... (rest of audio data)
`;
}

/**
 * Generates classic QBasic / QuickBASIC 4.5 source code
 */
export function generateQBasicSource(audio: ConvertedAudioData): string {
  const sampleRate = audio.sampleRate;
  const bytes = audio.raw8BitData;
  const previewLimit = Math.min(bytes.length, 128);

  let dataLines = '';
  for (let i = 0; i < previewLimit; i += 8) {
    const chunk: string[] = [];
    for (let j = 0; j < 8 && (i + j) < previewLimit; j++) {
      chunk.push(bytes[i + j].toString());
    }
    dataLines += `DATA ${chunk.join(', ')}\n`;
  }

  return `' =====================================================================
' QUICKBASIC 4.5 / QBASIC 8-BIT AUDIO PLAYER (COVOX LPT1 OR PC SPEAKER)
' Audio: ${audio.audioName} | Rate: ${sampleRate} Hz
' =====================================================================

CLS
PRINT "=== MS-DOS QBASIC 8-BIT AUDIO PLAYER ==="
PRINT "Sample Rate: ${sampleRate} Hz"
PRINT "Samples: ${audio.samplesCount}"
PRINT "Playing on LPT1 (Port &H378)... Press ESC to halt."

LPT1% = &H378
RESTORE AudioData

FOR i& = 1 TO ${previewLimit}
    READ SampleByte%
    OUT LPT1%, SampleByte%
    
    ' Calibrated timing loop
    FOR d% = 1 TO 35: NEXT d%

    IF INKEY$ = CHR$(27) THEN EXIT FOR
NEXT i&

OUT LPT1%, 0
PRINT "Playback complete. Returning to DOS."
END

AudioData:
${dataLines}
`;
}

/**
 * Generates DOSBox execution commands
 */
export function generateDosBoxGuide(binaryName: string = 'AUDIO.EXE'): string {
  return `# === HOW TO RUN IN DOSBOX / FREEDOS ===
1. Create a folder (e.g. C:\\DOSGAMES\\AUDIO)
2. Save your downloaded ${binaryName} into that folder
3. Launch DOSBox and execute:

   Z:\\> MOUNT C C:\\DOSGAMES\\AUDIO
   Z:\\> C:
   C:\\> ${binaryName}

The executable runs directly on real 8086/286/386/486/Pentium CPU in 16-bit real mode!
`;
}
